### ISSUE TITLE
ERROR: Could not build wheels for diff-gaussian-rasterization, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by BeckyWang0222** [graphdeco-inria/diff-gaussian-rasterization#71]
ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "D:\Anaconda\envs\gaussiancube\Lib\site-packages\torch\utils\cpp_extension.py", line 2104, in _run_ninja_build
          subprocess.run(
        File "D:\Anaconda\envs\gaussiancube\Lib\subprocess.py", line 571, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "E:\HUST\pg1\GaussianCube\diff-gaussian-rasterization\setup.py", line 17, in <module>
          setup(
        File "D:\Anaconda\envs\gaussiancube\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\Anaconda\envs\gaussiancube\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "D:\Anaconda\envs\gaussiancube\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "D:\Anaconda\envs\gaussiancube\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "D:\Anaconda\envs\gaussiancube\Lib\site-packages\setuptools\dist.py", line 989, in run_command
          super().run_command(command)
        File "D:\Anaconda\envs\gaussiancube\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "D:\Anaconda\envs\gaussiancube\Lib\site-packages\wheel\bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "D:\Anaconda\envs\gaussiancube\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "D:\Anaconda\envs\gaussiancube\Lib\site-packages\setuptools\dist.py", line 989, in run_command
          super().run_command(command)
        File "D:\Anaconda\envs\gaussiancube\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "D:\Anaconda\envs\gaussiancube\Lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "D:\Anaconda\envs\gaussiancube\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "D:\Anaconda\envs\gaussiancube\Lib\site-packages\setuptools\dist.py", line 989, in run_command
          super().run_command(command)
        File "D:\Anaconda\envs\gaussiancube\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "D:\Anaconda\envs\gaussiancube\Lib\site-packages\setuptools\command\build_ext.py", line 88, in run
          _build_ext.run(self)
        File "D:\Anaconda\envs\gaussiancube\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
          self.build_extensions()
        File "D:\Anaconda\envs\gaussiancube\Lib\site-packages\torch\utils\cpp_extension.py", line 868, in build_extensions
          build_ext.build_extensions(self)
        File "D:\Anaconda\envs\gaussiancube\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "D:\Anaconda\envs\gaussiancube\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "D:\Anaconda\envs\gaussiancube\Lib\site-packages\setuptools\command\build_ext.py", line 249, in build_extension
          _build_ext.build_extension(self, ext)
        File "D:\Anaconda\envs\gaussiancube\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 548, in build_extension
          objects = self.compiler.compile(
                    ^^^^^^^^^^^^^^^^^^^^^^
        File "D:\Anaconda\envs\gaussiancube\Lib\site-packages\torch\utils\cpp_extension.py", line 840, in win_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
        File "D:\Anaconda\envs\gaussiancube\Lib\site-packages\torch\utils\cpp_extension.py", line 1784, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "D:\Anaconda\envs\gaussiancube\Lib\site-packages\torch\utils\cpp_extension.py", line 2120, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for diff-gaussian-rasterization
  Running setup.py clean for diff-gaussian-rasterization
Failed to build diff-gaussian-rasterization
ERROR: Could not build wheels for diff-gaussian-rasterization, which is required to install pyproject.toml-based projects
(gaussiancube) PS E:\HUST\pg1\GaussianCube>

**Comment by YuxinYao620** [comment]
Hi, may I ask if you have resolved it? I come across the same issue. Would you mind sharing the solution if possible? It will be very helpful. Thank you in advance!

**Comment by Abhi-0088** [comment]
@YuxinYao620 The build failed with a ninja: build stopped: subcommand failed error. Initially, the issue was caused by the GLM library, which wasn't correctly included. This was resolved by explicitly specifying the correct include path for GLM in setup.py:
`extra_compile_args={"nvcc": ["-I" + os.path.join(os.path.dirname(os.path.abspath(__file__)), "third_party/glm/")]}`

However, a new build failure occurred due to missing or uninitialized Git submodules.
The repository now uses Git submodules (e.g., for GLM or other dependencies), but they were not initialized after cloning.

 **Solution**
```
       # Option 1: Fresh Clone with submodules
       git clone --recursive https://github.com/graphdeco-inria/diff-gaussian-rasterization.git
```
                                                               
```
       # Option 2: If you've already cloned the repo
       git submodule update --init --recursive
```

**✅ After Submodules are Initialized**
 You can now successfully build the package:

      pip install -e .


**Please mark as solve if this helps you**

**Comment by raining258** [comment]
> [@YuxinYao620](https://github.com/YuxinYao620) The build failed with a ninja: build stopped: subcommand failed error. Initially, the issue was caused by the GLM library, which wasn't correctly included. This was resolved by explicitly specifying the correct include path for GLM in setup.py: `extra_compile_args={"nvcc": ["-I" + os.path.join(os.path.dirname(os.path.abspath(__file__)), "third_party/glm/")]}`
> 
> However, a new build failure occurred due to missing or uninitialized Git submodules. The repository now uses Git submodules (e.g., for GLM or other dependencies), but they were not initialized after cloning.
> 
> **Solution**
> 
> ```
>        # Option 1: Fresh Clone with submodules
>        git clone --recursive https://github.com/graphdeco-inria/diff-gaussian-rasterization.git
> ```
> 
> ```
>        # Option 2: If you've already cloned the repo
>        git submodule update --init --recursive
> ```
> 
> **✅ After Submodules are Initialized** You can now successfully build the package:
> 
> ```
>   pip install -e .
> ```
> 
> **Please mark as solve if this helps you**

 thhere are still the following errors

    RuntimeError: Error compiling objects for extension
    [end of output]
    note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by Abhi-0088** [comment]
@raining258  If you have correctly executed the above step that I mentioned then is the above problem you are facing different from the one I provided solution?
check the below commands are running or not

```
nvcc --version
nvidia-smi ( be sure that the cuda version matches or near (or lower) than the pytorch cuda version)
```

Ensure you have visual studio build tools 2019(with default c++ development tools installed) and above along with proper environment variable setup in your system as it is necessary for compilation. You can run the below command in the admin PowerShell terminal to check this setup is done correctly or not

`cl`

if the above still does not solve's your problem, provide the complete error message so that I can help you further.
